spring:
  main:
    banner-mode: off

logging:
  level:
    root: warn

links-checker:
  request-timeout-seconds: 30
  max-request-attempts: 3
  max-concurrent-hosts: 8
  user-agent: "Mozilla/5.0 (X11; Linux x86_64; rv:143.0) Gecko/20100101 Firefox/143.0"
  sites-to-skip:
    - "https://www.babelio.com"
    - "https://www.7switch.com"
    - "https://www.placedeslibrairgbvfes.fr"
    - "https://www.japantimes.co.jp"
    - "https://www.telegraph.co.uk"
    - "https://www.youtube.com"
    - "https://www.badscience.net/"
    - "https://shs.cairn.info"