spring:
  main:
    banner-mode: off

links-checker:
  request-timeout-seconds: 30
  sites-to-skip:
    - "https://www.babelio.com"
    - "https://www.7switch.com"
    - "https://www.placedeslibraires.fr"
    - "https://www.japantimes.co.jp"
    - "https://www.telegraph.co.uk"
    - "https://www.youtube.com"